_target_: src.hyperparameters.cnn_hyperparameters.CNNHyperparameters

num_layers: MISSING
kernel_size: MISSING
conv_stride: MISSING
initial_channel_size: MISSING
channels_factor: MISSING
dropout: MISSING
max_pool_size: MISSING
activation: ReLU
normalize_model_outputs: False
use_global_avg_pooling: True #only for TCN
num_downsample_layers: 0  #only for TCN
